name: setup
description: setup node and yarn install
runs:
  using: "composite"
  steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn
        always-auth: true
        registry-url: https://npm.pkg.github.com

    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
